/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EANDROIDOS_AUTODEFS_H
#define S3EANDROIDOS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ANDROIDOS_NAME "s3eAndroidOS"
#define S3E_EXT_ANDROIDOS_HASH 0x4ac91e13

#endif /* !S3EANDROIDOS_AUTODEFS_H */
